baseURL = 'https://solo.hiero.org/'
languageCode = 'en-us'
title = 'Solo'
theme = "hugo-geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

enableGitInfo = true


# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
    [markup.goldmark.renderer]
        # Needed for mermaid shortcode
        unsafe = true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 9

[markup.highlight]
style = "vs"

[[module.mounts]]
source = "layouts"
target = "layouts"

[taxonomies]
tag = "tags"

[params]
    # (Optional, default false) Render menu from data file in 'data/menu/main.yaml'.
    # See also https://geekdocs.de/usage/menus/#bundle-menu.
    geekdocMenuBundle = true
    # (Optional, default false) Display search results with the parent folder as prefix. This
    # option allows you to distinguish between files with the same name in different folders.
    # NOTE: This parameter only applies when 'geekdocSearch = true'.
    geekdocSearchShowParent = true
    # Set to true to make a section foldable in side menu.
    geekdocCollapseSection = true
    # Add an anchor link to headlines.
    geekdocAnchor = true

[minify]
disableHTML = true
